#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TodoTask.Resource", IsApplication=true)]

namespace TodoTask
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040007
			public const int ab_background = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int action_bar_title_color = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int main_background = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int xam_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int xam_dark_blue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int xam_gray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int xam_green = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int xam_light_gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int xam_purple = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int del = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int done = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int processing = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int save = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int addTask = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int cbSl = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int delTask = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int detail_menu_del = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int detail_menu_done = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int detail_menu_edit = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int detail_tv_content = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int detail_tv_title = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int doneTask = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int etContent = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int etTitle = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int imgStatus = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int listTodo = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int saveTask = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int tvDate = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int tvTitle = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListViewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Modify = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int menu_detail = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int menu_modify = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int HintContentEditText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int HintTitleEditText = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int XamActionBarStyle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int XamActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int XamActionBarTitleStyle = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
